# Kickoff default config

# color format: rgb or rgba, if transparency is desired
color_background = '#282c34aa'
color_prompt = '#abb2bfff'
color_text = '#ffffffff'           # for search results
color_text_query = '#e5c07bff'     # for the search query
color_text_selected = '#61afefff'  # for the currently selected result

# Characters shown in front of the query.
prompt = ''

# space between window border and the content in pixel
padding = 100

font = ''  # otf or ttf only
font_size = 32.0
